import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { NextUIProvider } from "@nextui-org/react";
import Navbar from "./_components/Navbar";
import ReactQueryProvider from "./_components/ReactQueryProvider";;
import RecoilRootProvider from "./RecoilRootProvider";
import GoogleOAuthProviderComponent from "./GoogleOAuthProvider";
import { Toaster } from "react-hot-toast";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
    <body className={inter.className}>
          <RecoilRootProvider>
      <ReactQueryProvider>
        <GoogleOAuthProviderComponent>
            <NextUIProvider>   
          <div className="overflow-x-hidden">
          {children} 
          </div> 
            </NextUIProvider>
        </GoogleOAuthProviderComponent>
      </ReactQueryProvider>
          </RecoilRootProvider>
      <Toaster />
    </body>
  </html>
  );
}
